package:
  name: "pydft"
  version: "0.6.2"

source:
  path: .

build:
  noarch: python

requirements:
  build:
    - python>=3.9

  host:
    - pip
    - python>=3.9
    - setuptools
    - numpy

  run:
    - python>=3.9
    - scipy
    - numpy

test:
  requires:
    - numpy
    - nose
    - scipy
    - conda
    - packaging
    - python>=3.9
  source_files:
    - tests/*.py

about:
  home: https://gitlab.tue.nl/ifilot/pydft
  license: GPL3
  license_family: GPL
  summary: Python package for performing simple DFT calculations
  description: See the package README.md for more information.