package:
  name: "pydft"
  version: "0.6.4"

source:
  path: .

build:
  noarch: python

requirements:
  build:
    - python>=3.9

  host:
    - pip
    - python>=3.9
    - setuptools
    - numpy

  run:
    - python>=3.9
    - scipy
    - numpy
    - conda-forge::mendeleev
    - ifilot::pyqint
    - ifilot::pylebedev

test:
  requires:
    - numpy
    - scipy
    - setuptools
    - pytest
    - conda-forge::mendeleev
    - ifilot::pyqint
    - ifilot::pylebedev
  source_files:
    - tests/*.py
  commands:
    - pytest

about:
  home: https://github.com/ifilot/pydft
  license: GPL3
  license_family: GPL
  summary: Python package for performing simple DFT calculations
  description: See the package README.md for more information.