[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pydft"
version = "0.9.0"
authors = [
  { name="Ivo Filot", email="ivo@ivofilot.nl" }
]
maintainers = [
    { name="Ivo Filot", email="ivo@ivofilot.nl" },
]
description = "Localized-orbital Density Functional Theory code for educational purposes. "
readme = "README.md"
requires-python = ">=3.9"
license = {text = "GPL-3.0-or-later"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "scipy>=1.15",
    "numpy",
    "pyqint>=1.2",
    "pylebedev",
    "matplotlib",
    "numba"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["pydft*"]

[project.urls]
"Homepage" = "https://github.com/ifilot/pydft"
"Bug Tracker" = "https://github.com/ifilot/pydft/issues"