[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pydft"
version = "1.1.0"
authors = [
  { name="Ivo Filot", email="ivo@ivofilot.nl" }
]
maintainers = [
    { name="Ivo Filot", email="ivo@ivofilot.nl" },
]
description = "Localized-orbital Density Functional Theory code for educational purposes. "
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GPL-3.0-or-later"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Intended Audience :: Education",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Operating System :: OS Independent",
]
dependencies = [
    "scipy>=1.15",
    "numpy",
    "pyqint>=1.2",
    "pylebedev",
    "numba"
]

[project.optional-dependencies]
plot = [
    "matplotlib",
]
examples = [
    "matplotlib",
    "pytessel",
]
test = [
    "coverage[toml]",
    "pytest",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["pydft*"]

[tool.coverage.run]
branch = true
source = ["pydft"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[project.urls]
"Homepage" = "https://github.com/ifilot/pydft"
"Bug Tracker" = "https://github.com/ifilot/pydft/issues"
